#!/bin/bash
#
# Sign a built AgentBar.app so that the embedded Sparkle framework keeps working: its XPC
# services and helpers carry their own signatures and must be signed individually, never with
# --deep from the app.
#
#   scripts/sign-app.sh /path/to/AgentBar.app
#   SIGN_IDENTITY="Developer ID Application: …" scripts/sign-app.sh /path/to/AgentBar.app
#
# Signing order follows Sparkle's documentation: XPC services → Autoupdate → Updater.app →
# framework → app. SIGN_IDENTITY defaults to the ad-hoc identity ("-") for local builds;
# scripts/release.sh passes the Developer ID certificate so the build can be notarized.
#
# The app is not sandboxed, so there is no container to protect; the hardened-runtime /
# ad-hoc distinction still holds (see below).
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENTITLEMENTS="$ROOT/Supporting/AgentBar.entitlements"   # generated by `make generate`
SIGN_IDENTITY="${SIGN_IDENTITY:--}"

APP_PATH="${1:-}"
[ -d "$APP_PATH" ] || { echo "Usage: $0 /path/to/AgentBar.app" >&2; exit 1; }
[ -f "$ENTITLEMENTS" ] || { echo "Entitlements file missing: $ENTITLEMENTS (run: make generate)" >&2; exit 1; }

# Two flags only make sense on the Developer ID path:
#   --timestamp       notarization requires a secure timestamp; ad-hoc signatures cannot get one.
#   --options runtime on the app itself. The hardened runtime enables library validation, which
#                     only accepts embedded code signed by the same Team ID — an ad-hoc signature
#                     has no Team ID, so an ad-hoc app with the hardened runtime refuses to load
#                     its own Sparkle.framework.
if [ "$SIGN_IDENTITY" = "-" ]; then
  TIMESTAMP=""
  APP_RUNTIME=""
else
  TIMESTAMP="--timestamp"
  APP_RUNTIME="--options runtime"
fi

sign() { codesign --force --sign "$SIGN_IDENTITY" $TIMESTAMP "$@" 2>&1 | grep -v "replacing existing signature" || true; }

SPARKLE="$APP_PATH/Contents/Frameworks/Sparkle.framework"
if [ -d "$SPARKLE" ]; then
  V="$SPARKLE/Versions/B"
  [ -d "$V/XPCServices/Installer.xpc" ]  && sign --options runtime --preserve-metadata=entitlements "$V/XPCServices/Installer.xpc"
  [ -d "$V/XPCServices/Downloader.xpc" ] && sign --options runtime --preserve-metadata=entitlements "$V/XPCServices/Downloader.xpc"
  [ -f "$V/Autoupdate" ]                 && sign --options runtime "$V/Autoupdate"
  [ -d "$V/Updater.app" ]                && sign --options runtime "$V/Updater.app"
  sign --options runtime "$SPARKLE"
fi

# Any other embedded frameworks/helpers (none today, but keep the app signature valid if added).
for fw in "$APP_PATH"/Contents/Frameworks/*; do
  [ -e "$fw" ] || continue
  case "$fw" in *Sparkle.framework) continue ;; esac
  sign --options runtime "$fw"
done

# The widget extension: sandboxed, with its own entitlements (the App Group), signed
# before the app that embeds it. Always with the hardened runtime: an extension is loaded
# by the system, which requires it even for local builds.
for appex in "$APP_PATH"/Contents/PlugIns/*.appex; do
  [ -e "$appex" ] || continue
  NAME="$(basename "$appex" .appex)"
  APPEX_ENTITLEMENTS="$ROOT/Supporting/$NAME.entitlements"
  [ -f "$APPEX_ENTITLEMENTS" ] || { echo "Entitlements file missing: $APPEX_ENTITLEMENTS (run: make generate)" >&2; exit 1; }
  sign --options runtime --entitlements "$APPEX_ENTITLEMENTS" "$appex"
done

# The app itself, last, with its entitlements (no --deep: it would overwrite the nested signatures above).
sign $APP_RUNTIME --entitlements "$ENTITLEMENTS" "$APP_PATH"

codesign --verify --deep --strict "$APP_PATH"
APP_ENTITLEMENTS="$(codesign -d --entitlements - "$APP_PATH" 2>/dev/null || true)"
# get-task-allow marks a build as debuggable; Apple rejects it during notarization.
if echo "$APP_ENTITLEMENTS" | grep -q "com.apple.security.get-task-allow"; then
  echo "Signed app carries com.apple.security.get-task-allow — Apple would reject it" >&2; exit 1
fi
[ -d "$SPARKLE" ] && codesign --verify --deep --strict "$SPARKLE"

if [ "$SIGN_IDENTITY" != "-" ]; then
  DETAILS="$(codesign -dv --verbose=2 "$APP_PATH" 2>&1)"
  echo "$DETAILS" | grep -q "flags=.*runtime" || { echo "Signed app is missing the hardened runtime" >&2; exit 1; }
  echo "$DETAILS" | grep -q "^Timestamp=" || { echo "Signed app has no secure timestamp" >&2; exit 1; }
  echo "signed: $(echo "$DETAILS" | sed -n 's/^Authority=//p' | head -1) (hardened runtime, timestamped)"
else
  echo "signed: $(codesign -dv "$APP_PATH" 2>&1 | grep -E '^(Signature|CodeDirectory)' | tr '\n' ' ')"
fi
